import { Suspense } from "react";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { LangProvider } from "./context/LangContext";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Suspense fallback={null}>
          <ThemeProvider attribute="class" defaultTheme="system">
            <LangProvider>{children}</LangProvider>
          </ThemeProvider>
        </Suspense>
      </body>
    </html>
  );
}
